---
services:
  aws.greengrass.Nucleus:
    # version: "2.16.1"
  aws.greengrass.FleetProvisioningByClaim:
    configuration:
      rootPath: "/greengrass/v2"
      awsRegion: "us-east-1"
      # aws iot describe-endpoint --endpoint-type iot:Data-ATS --query endpointAddress --output text
      iotDataEndpoint: "device-data-prefix-ats.iot.us-east-1.amazonaws.com"
      # # aws iot describe-endpoint --endpoint-type iot:CredentialProvider --query endpointAddress --output text
      iotCredentialEndpoint: "device-credentials-prefix.credentials.iot.us-east-1.amazonaws.com"
      iotRoleAlias: "GreengrassCoreTokenExchangeRoleAlias"
      provisioningTemplate: "GreengrassFleetProvisioningTemplate"
      claimCertificatePath: "/greengrass/v2/claim-certs/claim.pem.crt"
      claimCertificatePrivateKeyPath: "/greengrass/v2/claim-certs/claim.private.pem.key"
      rootCaPath: "/greengrass/v2/AmazonRootCA1.pem"
      templateParameters:
        ThingName: "MyGreengrassCore"
        ThingGroupName: "MyGreengrassCoreGroup"
