#!/usr/bin/env bash

case "$1" in
"deployment")
    sudo /greengrass/v2/bin/greengrass-cli deployment create \
        --recipeDir ~/greengrassv2/recipes \
        --artifactDir ~/greengrassv2/artifacts \
        --merge "com.example.HelloWorld=1.0.0"
    ;;
"list")
    sudo /greengrass/v2/bin/greengrass-cli component list
    ;;
"log")
    sudo tail -f /greengrass/v2/logs/greengrass.log
    ;;
*) ;;
esac
